using Microsoft.EntityFrameworkCore;
using yet_enibla.Web.Models;

namespace yet_enibla.Web.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    // To use the Id column in the model as the identity column and it will
    // become auto-generated by default when trying to decide the primary key
    protected override void OnModelCreating(ModelBuilder modelBuilder) =>
        modelBuilder.UseIdentityAlwaysColumns();

    public DbSet<Restaurant>? Restaurants { get; set; }
    public DbSet<Owner>? Owners { get; set; }
}

