INSERT INTO "Restaurants" ("Name", "Description", "PhoneNumber", "Website", "Address", "City", "Country")
VALUES
('Marcus Addis Restaurant & Sky Bar', 'Experience dining at Marcus Addis Restaurant & Sky Bar.', '+251911000001', 'https://marcusaddisrestaurantskybar.com', '123 Marcus St', 'Addis Ababa', 'Ethiopia'),
('Gazebo Restaurant on the Park', 'Experience dining at Gazebo Restaurant on the Park.', '+251911000002', 'https://gazeborestaurantonthepark.com', '123 Gazebo St', 'Addis Ababa', 'Ethiopia'),
('Hotto', 'Experience dining at Hotto.', '+251911000003', 'https://hotto.com', '123 Hotto St', 'Addis Ababa', 'Ethiopia'),
('The Kitchen', 'Experience dining at The Kitchen.', '+251911000004', 'https://thekitchen.com', '123 The St', 'Addis Ababa', 'Ethiopia'),
('London Cafe & Satellite Restaurant', 'Experience dining at London Cafe & Satellite Restaurant.', '+251911000005', 'https://londoncafesatelliterestaurant.com', '123 London St', 'Addis Ababa', 'Ethiopia'),
('Yod Abyssinia Traditional Food', 'Experience dining at Yod Abyssinia Traditional Food.', '+251911000006', 'https://yodabyssiniatraditionalfood.com', '123 Yod St', 'Addis Ababa', 'Ethiopia'),
('Cravings Restaurant & Bar', 'Experience dining at Cravings Restaurant & Bar.', '+251911000007', 'https://cravingsrestaurantbar.com', '123 Cravings St', 'Addis Ababa', 'Ethiopia'),
('The Oriental', 'Experience dining at The Oriental.', '+251911000008', 'https://theoriental.com', '123 The St', 'Addis Ababa', 'Ethiopia'),
('Trattoria Gusto', 'Experience dining at Trattoria Gusto.', '+251911000009', 'https://trattoriagusto.com', '123 Trattoria St', 'Addis Ababa', 'Ethiopia'),
('Bait Al Mandi', 'Experience dining at Bait Al Mandi.', '+251911000010', 'https://baitalmandi.com', '123 Bait St', 'Addis Ababa', 'Ethiopia'),
('TinyTalian', 'Experience dining at TinyTalian.', '+251911000011', 'https://tinytalian.com', '123 TinyTalian St', 'Addis Ababa', 'Ethiopia'),
('Kategna Restaurant', 'Experience dining at Kategna Restaurant.', '+251911000012', 'https://kategnarestaurant.com', '123 Kategna St', 'Addis Ababa', 'Ethiopia'),
('Gusto Restaurant', 'Experience dining at Gusto Restaurant.', '+251911000013', 'https://gustorestaurant.com', '123 Gusto St', 'Addis Ababa', 'Ethiopia'),
('Cascara Coffee & Cocktail''s', 'Experience dining at Cascara Coffee & Cocktail''s.', '+251911000014', 'https://cascaracoffeecocktails.com', '123 Cascara St', 'Addis Ababa', 'Ethiopia'),
('Lucy Lounge & Restaurant', 'Experience dining at Lucy Lounge & Restaurant.', '+251911000015', 'https://lucyloungerestaurant.com', '123 Lucy St', 'Addis Ababa', 'Ethiopia'),
('Five Loaves Bistro and Bakery', 'Experience dining at Five Loaves Bistro and Bakery.', '+251911000016', 'https://fiveloavesbistroandbakery.com', '123 Five St', 'Addis Ababa', 'Ethiopia'),
('Castelli Restaurant', 'Experience dining at Castelli Restaurant.', '+251911000017', 'https://castellirestaurant.com', '123 Castelli St', 'Addis Ababa', 'Ethiopia'),
('Sishu', 'Experience dining at Sishu.', '+251911000018', 'https://sishu.com', '123 Sishu St', 'Addis Ababa', 'Ethiopia'),
('2000 Habesha Cultural Restaurant', 'Experience dining at 2000 Habesha Cultural Restaurant.', '+251911000019', 'https://2000habeshaculturalrestaurant.com', '123 2000 St', 'Addis Ababa', 'Ethiopia'),
('Meskott Culinary Experience', 'Experience dining at Meskott Culinary Experience.', '+251911000020', 'https://meskottculinaryexperience.com', '123 Meskott St', 'Addis Ababa', 'Ethiopia'),
('OM Indian Bistro', 'Experience dining at OM Indian Bistro.', '+251911000021', 'https://omindianbistro.com', '123 OM St', 'Addis Ababa', 'Ethiopia'),
('Entoto Restaurant', 'Experience dining at Entoto Restaurant.', '+251911000022', 'https://entotorestaurant.com', '123 Entoto St', 'Addis Ababa', 'Ethiopia'),
('Club Juventus', 'Experience dining at Club Juventus.', '+251911000023', 'https://clubjuventus.com', '123 Club St', 'Addis Ababa', 'Ethiopia'),
('Verres En Vers', 'Experience dining at Verres En Vers.', '+251911000024', 'https://verresenvers.com', '123 Verres St', 'Addis Ababa', 'Ethiopia'),
('Makush Art Gallery & Italian Restaurant', 'Experience dining at Makush Art Gallery & Italian Restaurant.', '+251911000025', 'https://makushartgalleryitalianrestaurant.com', '123 Makush St', 'Addis Ababa', 'Ethiopia'),
('Villaverde Addis Ababa', 'Experience dining at Villaverde Addis Ababa.', '+251911000026', 'https://villaverdeaddisababa.com', '123 Villaverde St', 'Addis Ababa', 'Ethiopia'),
('Belvedere Restaurant', 'Experience dining at Belvedere Restaurant.', '+251911000027', 'https://belvedererestaurant.com', '123 Belvedere St', 'Addis Ababa', 'Ethiopia'),
('Dashen Traditional Ethiopian Restaurant', 'Experience dining at Dashen Traditional Ethiopian Restaurant.', '+251911000028', 'https://dashentraditionalethiopianrestaurant.com', '123 Dashen St', 'Addis Ababa', 'Ethiopia'),
('Effoi Pizza', 'Experience dining at Effoi Pizza.', '+251911000029', 'https://effoipizza.com', '123 Effoi St', 'Addis Ababa', 'Ethiopia'),
('The Exclusive Dine & Wine', 'Experience dining at The Exclusive Dine & Wine.', '+251911000030', 'https://theexclusivedinewine.com', '123 The St', 'Addis Ababa', 'Ethiopia');
